CREATE TABLE `scott`.`booklist` (  /*스키마명.테이블 명*/
  `NUM` INT NOT NULL AUTO_INCREMENT,
  `SUBJECT` VARCHAR(100) NOT NULL,
  `MAKEYEAR` INT NOT NULL,
  `INPRICE` INT NOT NULL,
  `RENTPRICE` INT NOT NULL,
  `GRADE` VARCHAR(6) NULL DEFAULT 'ALL',
  PRIMARY KEY (`NUM`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '도서 목록';

SELECT * FROM SCOTT.BOOKLIST;

CREATE TABLE `scott`.`memberlist` (
  `NUM` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(30) NOT NULL,
  `BIRTH` DATE NOT NULL,
  `BPOINT` INT NULL,
  `JOINDATE` DATETIME NULL DEFAULT NOW(),
  `AGE` INT NULL,
  `GENDER` VARCHAR(3) NULL,
  PRIMARY KEY (`NUM`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = '회원 목록';

ALTER TABLE `scott`.`memberlist` 
ADD COLUMN `PHONE` VARCHAR(45) NOT NULL AFTER `NAME`,
CHANGE COLUMN `BPOINT` `BPOINT` INT NOT NULL DEFAULT 0 ,
CHANGE COLUMN `JOINDATE` `JOINDATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ;

CREATE TABLE `scott`.`rentlist` (
  `RENTDATE` DATETIME NULL DEFAULT NOW(),
  `NUMSEQ` INT NOT NULL AUTO_INCREMENT,
  `BOOKNUM` INT NULL,
  `MEMBERNUM` INT NULL,
  `DISCOUNT` INT NULL,
  `RENTLISTcol` VARCHAR(45) NULL,
  PRIMARY KEY (`NUMSEQ`))
COMMENT = '대여 목록';


ALTER TABLE `scott`.`rentlist` 
ADD INDEX `FK1_idx` (`BOOKNUM` ASC) VISIBLE,
ADD INDEX `FK2_idx` (`MEMBERNUM` ASC) VISIBLE;
;
ALTER TABLE `scott`.`rentlist` 
ADD CONSTRAINT `FK1`
  FOREIGN KEY (`BOOKNUM`)
  REFERENCES `scott`.`booklist` (`NUM`)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
ADD CONSTRAINT `FK2`
  FOREIGN KEY (`MEMBERNUM`)
  REFERENCES `scott`.`memberlist` (`NUM`)
  ON DELETE CASCADE
  ON UPDATE CASCADE;




