
CREATE TABLE PRODUCT_LIST (
	PD_NUM NUMBER(5) NOT NULL,
	NAME VARCHAR2(30),
	MAKEYEAR DATE DEFAULT SYSDATE,
	IN_PRI NUMBER(8) DEFAULT 0, 
	SELL_PRI NUMBER(8) DEFAULT 0,
	CONSTRAINT PL_PK1 PRIMARY KEY (PD_NUM)
)

CREATE SEQUENCE PD_SEQ START WITH 1 INCREMENT BY 1;

INSERT INTO PRODUCT_LIST VALUES (PD_SEQ.NEXTVAL, '컴퓨터', SYSDATE, 100, 130);
INSERT INTO PRODUCT_LIST VALUES (PD_SEQ.NEXTVAL, '마우스', SYSDATE, 1, 2);
INSERT INTO PRODUCT_LIST VALUES (PD_SEQ.NEXTVAL, '키보드', SYSDATE, 10, 15);
INSERT INTO PRODUCT_LIST VALUES (PD_SEQ.NEXTVAL, '모니터', SYSDATE, 12, 20);
INSERT INTO PRODUCT_LIST VALUES (PD_SEQ.NEXTVAL, '오디오', SYSDATE, 50, 70);

SELECT * FROM PRODUCT_LIST

