CREATE SEQUENCE MEMBER_SEQ START WITH 1 INCREMENT BY 1 
INSERT INTO MEMBERLIST(NUM, NAME, PHONE) VALUES(MEMBER_SEQ.NEXTVAL, '홍길동', '010-1111-2222');
INSERT INTO MEMBERLIST(NUM, NAME, PHONE) VALUES(MEMBER_SEQ.NEXTVAL, '홍길남', '010-1221-2222');
INSERT INTO MEMBERLIST(NUM, NAME, PHONE) VALUES(MEMBER_SEQ.NEXTVAL, '홍길서', '010-1331-2222');

SELECT * FROM MEMBERLIST