DROP SEQUENCE MEMBER_SEQ;

CREATE SEQUENCE MEMBER_SEQ START WITH 1 INCREMENT BY 1 ;
INSERT INTO MEMBERLIST(NUM, NAME, PHONE) VALUES(MEMBER_SEQ.NEXTVAL, '홍길동', '010-1111-2222');
INSERT INTO MEMBERLIST(NUM, NAME, PHONE) VALUES(MEMBER_SEQ.NEXTVAL, '홍길남', '010-1221-2222');
INSERT INTO MEMBERLIST(NUM, NAME, PHONE) VALUES(MEMBER_SEQ.NEXTVAL, '홍길서', '010-1331-2222');

SELECT * FROM MEMBERLIST;

DROP TABLE BOOKLIST PURGE;
DROP TABLE MEMBERLIST PURGE;
DROP TABLE RENTLIST PURGE;

CREATE TABLE booklist(
	booknum varchar2(5) NOT NULL,
	subject varchar2(30),
	makeyear number(4) DEFAULT 2021,
	inprice number(6) DEFAULT 0,
	rentprice number(6) DEFAULT 0, 
	constraint booknum_pk primary key(booknum)
)

SELECT MEMBER_SEQ.CURRVAL, MEMBER_SEQ.NEXTVAL FROM DUAL;


CREATE SEQUENCE BOOK_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE RENT_SEQ START WITH 1 INCREMENT BY 1;

DROP SEQUENCE MEMBER_SEQ;
DROP SEQUENCE RENT_SEQ;

CREATE SEQUENCE MEMBER_SEQ START WITH 4 INCREMENT BY 1;













