--라이브러리 함수 
-- *오라클 명령어 : 내장 함수 

SELECT * FROM TAB; 
SELECT * FROM DUAL;

SELECT 1234*1234 FROM DUAL;

SELECT LOWER('HONG KIL DONG') AS "소문자", 
UPPER('hong kil dong') AS "대문자", INITCAP('hong kil dong') AS "첫글자 대문자" FROM DUAL;

SELECT UPPER(ENAME) AS "UP-ENAME", LOWER(JOB) AS "LOW-JOB", INITCAP(JOB) AS "INIT-JOB" FROM EMP; 

SELECT LOWER('HONG KIL DONG') AS "소문자" FROM EMP;

--문자열 연결

SELECT CONCAT('ORACLE ', 'SQL') AS "CONCAT", 'ORACLE' || 'SQL' AS 문자열연결 FROM DUAL 


SELECT LENGTH('ORACLE SQL'), LENGTH('ORCLE') FROM DUAL; 
SELECT ENAME, LENGTH(ENAME) AS "LENGTH" FROM EMP;
SELECT SUBSTR('궤도밖에서, 나의 룸메이트에게',1, 9) FROM DUAL;

SELECT INSTR('궤도밖에서, 나의 룸메이트에게', '밖') FROM DUAL;
SELECT LPAD('그리고아무도없었다', 20, '#') AS "LPAD",
RPAD('그리고아무도없었다', 20, '*') AS "RPAD" FROM DUAL;

SELECT TRIM('A' FROM 'AAAAAAAORACLEAAAAA') AS RESULT,  
TRIM(' ', FROM '        ORACLE       ') AS RESULT2 FROM DUAL;

SELECT TRIM('A' FROM 'AAAAAAORACLEAAAAA') AS RESULT,
TRIM(' ' FROM '      O R A C L E      ') AS RESULT2 FROM DUAL;


SELECT ROUND(12.3456, 3), ROUND(1728.9382,-2) FROM DUAL;


SELECT ROUND(1728.9382,3), 
ROUND(1728.9382,3), 
ROUND(1728.9382,2), 
ROUND(1728.9382,1), 
ROUND(1728.9382,0), 
ROUND(1728.9382,-1), 
ROUND(1728.9382,-2), 
ROUND(1728.9382,-3)
FROM DUAL;


SELECT MOD(8,5) FROM DUAL;

SELECT ABS(-11) AS "ABS",
FLOOR(12.786542) AS "FLOOR",
CEIL(12.786542) AS "CEIL",
TRUNC(12.786542,3) AS "TRUNC" FROM DUAL;

SELECT SYSDATE FROM DUAL;

--날짜 관련

SELECT FLOOR(MONTHS_BETWEEN(SYSDATE, '2020-12-31')) FROM DUAL;
SELECT ADD_MONTHS(SYSDATE, 200) FROM DUAL;

SELECT NEXT_DAY(SYSDATE, '일요일'),
NEXT_DAY('2021-12-16', '토요일') FROM DUAL;

SELECT LAST_DAY(SYSDATE), LAST_DAY('2020-02-15') FROM DUAL;

SELECT TO_CHAR(SYSDATE,'YYYY-MM-DD') AS "TO_CHAR", 
TO_DATE('2002/2/2', 'YYYY/MM/DD') AS "TO_DATE" FROM DUAL; 


SELECT COMM/100 AS COMM_PCT, NVL(COMM, 1) AS COMM_NVL FROM EMP;

--거듭제곱, 제곱근
SELECT POWER(3,2), POWER(3,3.0001) FROM DUAL;
SELECT SQRT(2), SQRT(9) FROM DUAL;

--DECODE()
SELECT employee_id, emp_name, department_id, DECODE(department_id, 
	10, 'ACCOUNT',
	20, 'RESEARCH',
	30, 'SALES',
	40, 'OPERATION',
	50, 'SH_CHECK',
	60, 'IT_PROG',
	70, 'PR_REP',
	80, 'SA_REP',
	90, 'AD_PRES',
	100, 'FI_ACCOUNT',
	110, 'AC_ACCOUNT'
) AS "부서명" FROM employees;


select * from employees;

SELECT EMPLOYEE_ID, EMP_NAME, DEPARTMENT_ID,
	CASE WHEN DEPARTMENT_ID = 10 THEN 'ACCOUNT'
		WHEN DEPARTMENT_ID = 20 THEN 'RESEARCH'
		WHEN DEPARTMENT_ID = 30 THEN 'SALES'
		WHEN DEPARTMENT_ID = 40 THEN 'OPERATION'
		WHEN DEPARTMENT_ID = 50 THEN 'SH_CHECK'
		WHEN DEPARTMENT_ID = 60 THEN 'IT_PROG'
		WHEN DEPARTMENT_ID = 70 THEN 'PR_REP'
		WHEN DEPARTMENT_ID = 80 THEN 'SA_REP'
		WHEN DEPARTMENT_ID = 90 THEN 'AD_PRES'
		WHEN DEPARTMENT_ID = 100 THEN 'FI_ACCOUNT'
		WHEN DEPARTMENT_ID = 110 THEN 'AC_ACCOUNT'
	END AS "부서명"
FROM EMPLOYEES

SELECT MOD(19,4) AS MOD, REMAINDER(19,4) AS REMAINDER FROM DUAL;
SELECT MOD(19.1234,4.2) AS MOD, REMAINDER(19.1234,4.2) AS REMAINDER FROM DUAL;


SELECT REPLACE('괘도밖에서, 나의 룸메이트에게','괘', '궤') FROM DUAL;

SELECT TO_CHAR(12345678, '999,999,999') AS "TO_CHAR",
TO_DATE('20140101 13:44:50', 'YYYY-MM-DD HH24:MI:SS') AS "TO_DATE",
TO_NUMBER('123456') AS "TO_NUMBER" FROM DUAL;


SELECT TO_CHAR(SYSDATE,'AM') AS "AM/PM",
 TO_CHAR(SYSDATE,'YY"년"') AS YEAR,
 TO_CHAR(SYSDATE,'MONTH') AS MONTH,
 TO_CHAR(SYSDATE,'MON') AS MONTH
FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'D') FROM DUAL;	--일~토에 1~7의 숫자를 부여해 보여줌
SELECT TO_CHAR(SYSDATE, 'DAY') FROM DUAL; -- 요일 표시 
SELECT TO_CHAR(SYSDATE, 'DD') FROM DUAL; --일자를 01~31로 표시
SELECT TO_CHAR(SYSDATE, 'DDD') FROM DUAL; --일자를 001~365로 표시
SELECT TO_CHAR(SYSDATE, 'DL') FROM DUAL; --연월일요일 표시

SELECT
TO_CHAR(SYSDATE, 'D') AS "D", 		--일~토에 1~7의 숫자를 부여해 보여줌
TO_CHAR(SYSDATE, 'DAY') AS "DAY", 	-- 요일 표시 
TO_CHAR(SYSDATE, 'DD') AS "DD", 	--일자를 01~31로 표시
TO_CHAR(SYSDATE, 'DDD') AS "DDD",	--일자를 001~365로 표시
TO_CHAR(SYSDATE, 'DL') AS "DL" 		--연월일요일 표시
FROM DUAL;



--
SELECT TO_CHAR(SYSDATE, 'MI"분"') AS "MIN", 
TO_CHAR(SYSDATE, 'HH24"시" MI"분" SS"초"') AS "TIME" FROM DUAL;

















