SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE EMP_NAME = 'Douglas Grant'; 
SELECT DEPARTMENT_NAME, PARENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_ID = 50;
SELECT DEPARTMENT_NAME FROM DEPARTMENTS WHERE DEPARTMENT_ID = 10;

SELECT * FROM DEPARTMENTS

SELECT * FROM DEPT,EMP;

SELECT * FROM DEPT, EMP WHERE EMP.DEPTNO=DEPT.DEPTNO;

SELECT EMP.ENAME, EMP.DEPTNO, DEPT.DNAME, DEPT.LOC FROM DEPT, EMP
WHERE EMP.DEPTNO=DEPT.DEPTNO;

SELECT EMP_NAME, EMPLOYEES.DEPARTMENT_ID, DEPARTMENT_NAME, SALARY  FROM EMPLOYEES, DEPARTMENTS 
WHERE EMP_NAME = 'Douglas Grant' AND EMPLOYEES.DEPARTMENT_ID=DEPARTMENTS.DEPARTMENT_ID;

SELECT * FROM EMPLOYEES 

