SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE EMP_NAME = 'Douglas Grant'; 
SELECT DEPARTMENT_NAME, PARENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_ID = 50;
SELECT DEPARTMENT_NAME FROM DEPARTMENTS WHERE DEPARTMENT_ID = 10;

SELECT * FROM DEPARTMENTS

SELECT * FROM DEPT,EMP;

SELECT * FROM DEPT, EMP WHERE EMP.DEPTNO=DEPT.DEPTNO;

SELECT EMP.ENAME, EMP.DEPTNO, DEPT.DNAME, DEPT.LOC FROM DEPT, EMP
WHERE EMP.DEPTNO=DEPT.DEPTNO;

SELECT EMP_NAME, EMPLOYEES.DEPARTMENT_ID, DEPARTMENT_NAME, SALARY  FROM EMPLOYEES, DEPARTMENTS 
WHERE EMP_NAME = 'Douglas Grant' AND EMPLOYEES.DEPARTMENT_ID=DEPARTMENTS.DEPARTMENT_ID;

SELECT * FROM EMPLOYEES 

CREATE OR REPLACE VIEW RENTDETAIL AS 
SELECT TO_CHAR(A.RENTDATE, 'YYYY-MM-DD') AS RENTDATE, A.NUM AS RENTNUM, C.MEMBERNUM AS MEMBERNUM, C.NAME AS MEMBERNAME,
B.RENTPRICE-A.DISCOUNT AS PRICE, B.NUM AS BOOKNUM, B.SUBJECT AS SUBJECT
FROM RENTLIST A, BOOKLIST B, MEMBERLIST C 
WHERE A.BOOKNUM=B.NUM AND A.MEMBERNUM = C.MEMBERNUM
ORDER BY A.NUM DESC

SELECT * FROM RENTDETAIL
