CREATE TABLE STUDENT(
	STU_NO NUMBER(5) NOT NULL,
	NAME varchar2(20),
	AGE number(4),
	GENDER varchar2(5) DEFAULT '-',
	YEAR NUMBER(6) NOT NULL,
	GRADE VARCHAR2(5) DEFAULT 'F',
	CONSTRAINT STUDENT_PK PRIMARY KEY(STU_NO),
	CONSTRAINT GENDER_CHECK CHECK(GENDER IN ('F', 'M', '-')),
	CONSTRAINT AGE_CHECK CHECK(AGE BETWEEN 7 AND 18)
)

ALTER TABLE STUDENT ADD CLASS VARCHAR(5);
ALTER TABLE STUDENT MODIFY CLASS VARCHAR2(5);
ALTER TABLE STUDENT ADD CONSTRAINT STUDENT_FK FOREIGN KEY(CLASS) 
REFERENCES CLASS(CLASS)
--STUDENT TABLE CREATED
--PK : STU_NO
--FK : CLASS(CLASS)

DROP TABLE STUDENT

CREATE TABLE STU_GRADE (
	NAME VARCHAR2(20) NOT NULL,
	STU_NO NUMBER(5) NOT NULL PRIMARY KEY,
	MAT NUMBER(3),
	KOREAN NUMBER(3),
	ENGLISH NUMBER(3),
	CHEMISTRY NUMBER(3),
	BIOLOGY NUMBER(3),
	PHYSICS NUMBER(3)
)

SELECT * FROM STU_GRADE

ALTER TABLE STU_GRADE ADD CONSTRAINT GRADE_PK FOREIGN KEY(STU_NO)
REFERENCES STUDENT(STU_NO)

--STU_GRADE TABLE CREATED
--PK : STU_NO
--FK : SUT_NO


CREATE TABLE CLASS (
	CLASS VARCHAR2(5) NOT NULL PRIMARY KEY,
	CLASS_GRADE VARCHAR2(20) NOT NULL
)

--CLASS TABLE CREATED 

DELETE FROM STUDENT

INSERT INTO STUDENT VALUES (10102, '홍길동', 16, 'M', '1' ,'B', 2);
INSERT INTO STUDENT VALUES (10103, '이남길', 8, 'M', '1' ,'B', 2);
INSERT INTO STUDENT VALUES (10103, '이하윤', 9, 'M', '1' ,'B', 2);
INSERT INTO STUDENT VALUES (10103, '김서아', 9, 'M', '1' ,'B', 2);
INSERT INTO STUDENT VALUES (10104, '서길홍', 17, 'M', '1' ,'B', 2);
INSERT INTO STUDENT VALUES (10105, '주현아', 11, 'F', '1' ,'B', 2);
INSERT INTO STUDENT VALUES (10106, '김선호', 12, 'M', '1' ,'B', 2);
INSERT INTO STUDENT VALUES (10107, '고유정', 13, 'F', '1' ,'B', 2);
INSERT INTO STUDENT VALUES (10108, '김유정', 15, 'F', '1' ,'B', 2);
INSERT INTO STUDENT VALUES (10109, '이선미', 15, 'F', '1' ,'B', 2);
INSERT INTO STUDENT VALUES (10110, '최현우', 14, 'M', '1' ,'B', 2);
INSERT INTO STUDENT VALUES (10111, '김길태', 12, 'M', '1' ,'B', 2);
INSERT INTO STUDENT VALUES (10112, '여진구', 12, 'M', '1' ,'B', 2);
INSERT INTO STUDENT VALUES (10113, '조연우', 11, 'M', '1' ,'B', 2);
INSERT INTO STUDENT VALUES (10114, '김서윤', 7, 'F', '1' ,'B', 2);

SELECT * FROM STUDENT


INSERT INTO CLASS VALUES(1, 'S');
INSERT INTO CLASS VALUES(2, 'A');
INSERT INTO CLASS VALUES(3, 'B');
INSERT INTO CLASS VALUES(4, 'C');
INSERT INTO CLASS VALUES(5, 'D');















